value = input('Input: ')
print('type: {}'.format(type(value)))
print('istitle: {}'.format(value.istitle()))
print('isascii: {}'.format(value.isascii()))
print('isdecimal: {}'.format(value.isdecimal()))
